# Generated by Django 3.1a1 on 2020-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(upload_to='post_img/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
