# Generated by Django 3.0.7 on 2020-06-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0002_auto_20200615_0434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
