# Generated by Django 3.0.7 on 2020-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0004_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
