# Generated by Django 3.0.7 on 2020-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0006_auto_20200615_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pages_imgs/awareness/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BePositivePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pages_imgs/bePositive/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField(default=' ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pages_imgs/bePositive/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoronaFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='resource',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pages_imgs/news/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='toolspost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pages_imgs/tools/'),
        ),
        migrations.AlterField(
            model_name='toolspost',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
