# Generated by Django 3.0.7 on 2020-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0007_auto_20200617_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoronaFeature',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='toolspost',
            name='content',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
