# Generated by Django 3.0.7 on 2020-07-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0009_auto_20200704_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
